import {
  ABOUT_SUMMARY,
  CERTIFICATES,
  EXPERIENCE,
  getEntriesForSkill,
  getPaperByDoi,
  getProjectBySlug,
  getProjectsByTitles,
  getSkillBySlug,
  getSkillCategoryBySlug,
  isSkillSlug,
  NAVIGATION_ITEMS,
  PAPERS,
  PORTFOLIO_SKILLS,
  PROJECT_GROUPS,
  PROJECTS,
  SKILL_ASSETS,
  SKILL_CATEGORIES,
} from '~~/utils/portfolioContent'

export type {
  CertificateEntry,
  ExperienceEntry,
  ExperienceThesis,
  NavigationItem,
  PaperEntry,
  ProjectEntry,
  ProjectGalleryImage,
  ProjectGroup,
  SkillAssetEntry,
  SkillCategory,
  SkillItem,
  SkillSlug,
} from '~~/utils/portfolioContent'

export function usePortfolioData () {
  return {
    aboutSummary: ABOUT_SUMMARY,
    certificates: CERTIFICATES,
    experience: EXPERIENCE,
    getEntriesForSkill,
    getPaperByDoi,
    getProjectBySlug,
    getProjectsByTitles,
    getSkillBySlug,
    getSkillCategoryBySlug,
    isSkillSlug,
    navigationItems: NAVIGATION_ITEMS,
    papers: PAPERS,
    projectGroups: PROJECT_GROUPS,
    projects: PROJECTS,
    skillAssets: SKILL_ASSETS,
    skillCategories: SKILL_CATEGORIES,
    skills: PORTFOLIO_SKILLS,
  }
}
